# Perfil de Desenvolvimento Local (dev)
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  error:
    include-trace: true

logging:
  level:
    br.com.mmc.bilhetinho_api: DEBUG
